### ISSUE TITLE
Regarding the deployment of postgres

### ISSUE THREAD

**Issue by bizimunda** [StephenGrider/multi-k8s#16]
I was following your course on Udemy.
I have encountered an error while creating postgres-deoployment.
When we create **postgres deployment**, we cannot create it with without ENV parameter and otherwiese pod stays in **crashLoopBackOff** status.

So here is the code which works.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
```
You just need to add the env parameter and its values, initially to create it. But as we progress then we can change its value according to the course
